// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using userList.Models;

#nullable disable

namespace projectweb.Migrations
{
    [DbContext(typeof(usercontext))]
    [Migration("20240618091002_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("projectweb.Models.product", b =>
                {
                    b.Property<int>("productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productid"), 1L, 1);

                    b.Property<string>("productname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("productid");

                    b.HasIndex("userid");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            productid = 1,
                            productname = "car bm2",
                            userid = 1
                        },
                        new
                        {
                            productid = 2,
                            productname = "Comedy",
                            userid = 1
                        },
                        new
                        {
                            productid = 3,
                            productname = "Drama",
                            userid = 1
                        },
                        new
                        {
                            productid = 4,
                            productname = "Horror",
                            userid = 1
                        },
                        new
                        {
                            productid = 5,
                            productname = "Musical",
                            userid = 1
                        },
                        new
                        {
                            productid = 6,
                            productname = "RomCom",
                            userid = 1
                        },
                        new
                        {
                            productid = 7,
                            productname = "SciFi",
                            userid = 1
                        });
                });

            modelBuilder.Entity("projectweb.Models.user", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userid"), 1L, 1);

                    b.Property<string>("ccnum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userid");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            userid = 1,
                            ccnum = "11234",
                            email = "ahmadabualrob@gmail.com",
                            password = "123456789123456789",
                            phone = "056444322",
                            username = "ahmad"
                        });
                });

            modelBuilder.Entity("projectweb.Models.product", b =>
                {
                    b.HasOne("projectweb.Models.user", "user")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
